services:
  cube-cos-api-builder:
    build:
      context: ./build
      dockerfile: cube-cos-api-jail.Dockerfile
    platform: linux/amd64
    working_dir: /workspace
    volumes:
      - .:/workspace
    command: >
      sh -c "CGO_ENABLED=1 GOWORK=off GOOS=linux GOARCH=amd64 go build -a -o bin/cube-cos-api cmd/main.go"
