version: "3"

vars:
  apiService: "cube-cos-api"
  dbService: "cube-cos-mongo"
  devCosUser: "root"
  devCosIp: "<REPLACE_NEW_VALUE_HERE_FOR_DEVELOPING>"
  mongoVersion: "6.0.19"

tasks:
  check:
    cmds:
      - task: vet
      - task: diffMod
      - task: diffApiDocs
  build:
    cmds:
      - task: buildLocalBinary
  vet:
    cmds:
      - GOWORK=off go vet ./...
  diffMod:
    cmds:
      - GOWORK=off go mod tidy
      - git diff --exit-code go.mod go.sum
  diffApiDocs:
    cmds:
      - git diff --exit-code api
  test:
    cmds:
      - GOWORK=off go test -v ./...
  buildLocalBinary:
    cmds:
      - GOWORK=off GOOS=linux GOARCH=amd64 go build -o bin/{{.apiService}} cmd/main.go
  updateApiDocs:
    cmds:
      - swag init --output ./api -g ./cmd/main.go
      - swag fmt -d ./
  runLocalDevApi:
    cmds:
      - GOWORK=off go run cmd/main.go -conf configs/{{.apiService}}.yaml
  runLocalDevMongo:
    cmds:
      - docker run -d -p 27017:27017 --name {{.dbService}}-0 --hostname {{.dbService}}-0 mongo:{{.mongoVersion}} mongod --replSet cube-cos-rs
  deployAllRemoteDevServices:
    cmds:
      - task: deployRemoteDevApi
      - task: deployRemoteDevMongo
  deployRemoteDevApi:
    cmds:
      - task: buildLocalBinary
      - task: stopRemoteDevApi
      - task: initRemoteCosDevEnv
      - task: moveLocalBinaryToRemoteCos
      - task: moveLocalConfigToRemoteCos
      - task: activateSystemdService
  deployRemoteDevMongo:
    cmds:
      - task: initRemoteCosDevEnv
      - task: simulateRemoteProductionMongo
  stopRemoteDevApi:
    cmds:
      - ssh {{.devCosUser}}@{{.devCosIp}} "pkill -f {{.apiService}}"
    ignore_error: true
  simulateRemoteProductionMongo:
    cmds:
      - ssh {{.devCosUser}}@{{.devCosIp}} "docker run -itd -p 27017:27017 -v /etc/{{.apiService}}/mongo:/data/db --name {{.dbService}}-0 --network={{.dbService}} --hostname {{.dbService}}-0 mongo:{{.mongoVersion}} mongod --replSet {{.dbService}}"
      - ssh {{.devCosUser}}@{{.devCosIp}} "sleep 15"
      - ssh {{.devCosUser}}@{{.devCosIp}} 'docker exec -i {{.dbService}}-0 mongosh --quiet --eval "rs.initiate()"'
      - ssh {{.devCosUser}}@{{.devCosIp}} 'docker exec -i {{.dbService}}-0 mongosh --quiet --eval "db.getSiblingDB(\"admin\").createUser({user:\"admin\",pwd:\"admin\",roles:[{role:\"userAdminAnyDatabase\",db:\"admin\"}]})"'
  removeRemoteDevMongo:
    cmds:
      - ssh {{.devCosUser}}@{{.devCosIp}} "docker rm -f {{.dbService}}-0"
      - ssh {{.devCosUser}}@{{.devCosIp}} "rm -rf /etc/{{.apiService}}/mongo"
      - ssh {{.devCosUser}}@{{.devCosIp}} "docker network rm {{.dbService}}"
  initRemoteCosDevEnv:
    cmds:
      - task: initRemoteCosWorkspace
      - task: initRemoteCosContainerNetwork
  initRemoteCosWorkspace:
    cmds:
      - ssh {{.devCosUser}}@{{.devCosIp}} "mkdir -p /etc/{{.apiService}}"
      - ssh {{.devCosUser}}@{{.devCosIp}} "grep {{.apiService}} /etc/group || groupadd {{.apiService}}"
      - ssh {{.devCosUser}}@{{.devCosIp}} "id {{.apiService}} || useradd -g {{.apiService}} {{.apiService}}"
  initRemoteCosContainerNetwork:
    cmds:
      - ssh {{.devCosUser}}@{{.devCosIp}} "docker network ls | grep {{.dbService}} || docker network create {{.dbService}}"
    ignore_error: true
  moveLocalBinaryToRemoteCos:
    cmds:
      - scp bin/{{.apiService}} {{.devCosUser}}@{{.devCosIp}}:/usr/bin/{{.apiService}}
      - ssh {{.devCosUser}}@{{.devCosIp}} "chown -R {{.apiService}}:{{.apiService}} /usr/bin/{{.apiService}}"
  moveLocalConfigToRemoteCos:
    cmds:
      - scp configs/{{.apiService}}.yaml {{.devCosUser}}@{{.devCosIp}}:/etc/{{.apiService}}
      - scp init/cube-cos-api.service {{.devCosUser}}@{{.devCosIp}}:/lib/systemd/system
  activateSystemdService:
    cmds:
      - ssh {{.devCosUser}}@{{.devCosIp}} "systemctl daemon-reload"
      - ssh {{.devCosUser}}@{{.devCosIp}} "systemctl enable cube-cos-api.service"
      - ssh {{.devCosUser}}@{{.devCosIp}} "systemctl restart cube-cos-api.service"
